<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-78J31B7" failures="1" tests="3" name="Android 2" time="63.906" errors="0" timestamp="2023-10-04T21:13:10 GST">
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserPassword" time="8.938"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUsername" time="4.146">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fffdfff]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fffdfff]
at com.qa.tests.LoginTests.invalidUsername(LoginTests.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- invalidUsername -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="4.976"/>
</testsuite> <!-- Android 2 -->
